name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-southwest1
  REPOSITORY: terraform-cloud-mcp

jobs:
  build-and-deploy:
    name: build-and-deploy-terraform-mcp
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -f "./Dockerfile" \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/terraform-mcp:${{ github.sha }} \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/terraform-mcp:latest \
            .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/terraform-mcp:${{ github.sha }}
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/terraform-mcp:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update terraform-mcp-api \
            --image "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/terraform-mcp:${{ github.sha }}" \
            --region "$REGION" \
            --project "$PROJECT_ID" \
            --platform managed \
            --async